PUT 127.0.0.1:8012/private/project/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJhZG1pbiIsInNvdXJjZSI6InJlc3QifQ.b1mWEPDovS5SReQs2NuhnJLXNc7o4H3A89f3xi83RNc

{"title": "s1.pravoved.ru"}

###
PUT 127.0.0.1:8012/private/project/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJhZG1pbiIsInNvdXJjZSI6InJlc3QifQ.b1mWEPDovS5SReQs2NuhnJLXNc7o4H3A89f3xi83RNc

{"title": ""}


###

PUT 127.0.0.1:8012/pravoved.ru/event/

{"metricName": "backend_response", "durationMs": 301}

###

GET 127.0.0.1:8012/private/pravoved.ru/events/?metric_time_from=2019-08-02T00:00:00&metric_time_to=2019-08-10T00:00:00&group_by=minutes&metric_name=backend_response
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJhZG1pbiIsInNvdXJjZSI6InJlc3QifQ.b1mWEPDovS5SReQs2NuhnJLXNc7o4H3A89f3xi83RNc

###

POST 127.0.0.1:8012/login/

{"login": "admin", "password": "letmein"}

###
